apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "community-solid-server.fullname" . }}
  labels:
    {{- include "community-solid-server.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/**.json").AsConfig | nindent 2 }}
